# SPDX-FileCopyrightText: 2026 Simon Bruder <simon@sbruder.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

{ lib
, stdenv
, fetchFromGitHub
, fetchNpmDeps
, nodejs_22
, nodejs_24
, npmHooks
, dart-sass
, gradle_9
, makeWrapper
, jdk25_headless
, zip
, libwebp
}:
let
  jdk = jdk25_headless;

  pname = "komga";
  version = "1.26.3";

  src = fetchFromGitHub {
    owner = "gotson";
    repo = pname;
    rev = version;
    hash = "sha256-fFMa0WcIjNqBWtunOrN88INxUwTmSdtm6BihaRNhkhs=";
    leaveDotGit = true;
    postFetch = ''
      set -euo pipefail
      cd $out

      # normally generated by com.gorylenko.gradle-git-properties,
      # which requires the (non-reproducible) .git dir
      mkdir -p BOOT-INF/classes
      cat > BOOT-INF/classes/git.properties << EOF
      git.branch=master
      git.commit.id=$(git rev-parse HEAD)
      git.commit.time=$(git show --no-patch --format=%ci HEAD | sed -e 's/ /T/' -e 's/ //' -e 's/:/\\:/g')
      EOF

      rm -rf .git
    '';
  };

  webui = stdenv.mkDerivation (finalAttrs: {
    pname = "${pname}-webui";
    inherit version src;

    patches = [
      ./0001-fix-webui-do-not-open-popup-for-oauth2-login.patch
    ];
    patchFlags = [ "-p2" ];

    sourceRoot = "source/komga-webui";

    npmDeps = fetchNpmDeps {
      inherit src;
      inherit (finalAttrs) sourceRoot;
      hash = "sha256-WllmbyrFc04ipHuJJDjv2BdlrKfx1JrXxLRKoquVnd8=";
    };

    nativeBuildInputs = [
      nodejs_22
      npmHooks.npmConfigHook
      npmHooks.npmBuildHook
    ];

    npmBuildScript = "build";

    makeCacheWritable = true;

    installPhase = ''
      runHook preInstall
      mv dist $out
      runHook postInstall
    '';
  });

  next-ui = stdenv.mkDerivation (finalAttrs: {
    pname = "${pname}-next-ui";
    inherit version src;

    sourceRoot = "source/next-ui";

    npmDeps = fetchNpmDeps {
      inherit src;
      inherit (finalAttrs) sourceRoot;
      hash = "sha256-ZnU9LgJI6/96/d7kZnLn+CO06TQ8THDmP7+KCQoBh0c=";
    };

    nativeBuildInputs = [
      nodejs_24
      npmHooks.npmConfigHook
      npmHooks.npmBuildHook
    ];

    postConfigure = ''
      echo 'export const compilerCommand = ["${lib.getExe dart-sass}"]' > node_modules/sass-embedded/dist/lib/src/compiler-path.js
    '';

    npmBuildScript = "build:with-i18n";

    installPhase = ''
      runHook preInstall
      mv dist $out
      runHook postInstall
    '';
  });
in
stdenv.mkDerivation {
  inherit src pname version;

  nativeBuildInputs = [
    gradle_9
    makeWrapper
  ];

  mitmCache = gradle_9.fetchDeps {
    inherit pname;
    # merged so it builds under both 26.05 and unstable
    # jq --indent 1 -s '.[0] * .[1]' deps.json deps-stable.json > deps-merged.json
    data = ./deps.json;
  };

  postPatch = ''
    # see postFetch in src
    substituteInPlace komga{,-tray}/build.gradle.kts \
      --replace-fail "alias(libs.plugins.gradleGitProperties)" ""

    cp -r --no-preserve=mode ${webui} komga-webui/dist
    cp -r --no-preserve=mode ${next-ui} next-ui/dist
  '';

  gradleFlags = [ "-Dorg.gradle.java.home=${jdk}" ];

  gradleBuildTask = ":komga:webuiCopyIndex :komga:nextuiCopyIndex :komga:bootJar";

  postBuild = ''
    # see postFetch in src
    ${lib.getExe zip} -u komga/build/libs/${pname}-${version}.jar BOOT-INF/classes/git.properties
  '';

  installPhase = ''
    runHook preInstall

    install -Dm444 komga/build/libs/${pname}-${version}.jar $out/share/${pname}/${pname}-${version}.jar
    makeWrapper ${jdk}/bin/java $out/bin/${pname} \
      --add-flags "-jar $out/share/${pname}/${pname}-${version}.jar" \
      --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ libwebp ]}

    runHook postInstall
  '';

  meta = {
    description = "Media server for comics/mangas/BDs/magazines/eBooks with API, OPDS, Kobo Sync and KOReader Sync support";
    homepage = "https://komga.org";
    license = lib.licenses.mit;
    platforms = jdk.meta.platforms;
    maintainers = with lib.maintainers; [ sbruder ];
    mainProgram = pname;
    sourceProvenance = with lib.sourceTypes; [ fromSource binaryBytecode ];
  };
}
