# SPDX-FileCopyrightText: 2026 Simon Bruder <simon@sbruder.de>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

labels:
  backend: local

when:
  - event: manual
  - event: push
  - event: cron

steps:
  - name: check pinned
    image: bash
    commands:
      - nix run .#check-all-packages >> out_paths

  - name: check 26.05
    image: bash
    commands:
      - nix run .#check-all-packages -- --override-input nixpkgs github:nixos/nixpkgs/nixos-26.05 >> out_paths
    failure: ignore

  - name: check unstable
    image: bash
    commands:
      - nix run .#check-all-packages -- --override-input nixpkgs github:nixos/nixpkgs/nixos-unstable >> out_paths
    failure: ignore

  - name: setup attic
    image: bash
    environment:
      XDG_CONFIG_HOME: $PWD/.config
    commands:
      - attic login hiroshi https://nix-cache.sbruder.de/ "$ATTIC_TOKEN"
      - attic push ci --stdin < out_paths
